### ISSUE TITLE
Is your code with FPN

### ISSUE THREAD

**Issue by MrWanter** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#2]
As recommended in this github repo: https://github.com/yangxue0827/FPN_Tensorflow, I'm wondering is your implementation for FPN?

**Comment by yangxue0827** [comment]
We are trying, but the FPN currently implemented is 10% lower than the Faster-RCNN. @MrWanter

**Comment by MrWanter** [comment]
The result of 77.03 of resnet101 for train and test on voc07 is really significant, pytorch implementation get 75.2https://github.com/jwyang/faster-rcnn.pytorch , tf-faster-rcnn get 75.7 https://github.com/endernewton/tf-faster-rcnn do you confirm it is training on voc07 and test on voc07 with resnet101 backbone? if so, can you suggest what part of difference of this code base that may generate that ~2 mAP gap, which is really huge

**Comment by yangJirui** [comment]
yeah, we only use train_and_val dataset of  Voc07 for training. 
In my experience, reducing the weight of location loss is helpful to  improve the mAP (refer the cfgs.py for detail). You can also do some experiments yourself on VOC07.

However, our codes only performs about 29.0+ in COCO 2017,(only use the trainSet without valSet for training). We think this performance is not so good, although we don’t know how other code performs on coco2017. (Most of codes only report the performance in coco2014).

Due to the restriction of GPU, we have not  do more experiments on COCO2017.  We welcome you to make some changes to improve the performance on COCO 2017. @MrWanter
