### ISSUE TITLE
Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,21]

### ISSUE THREAD

**Issue by leetesua** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#5]
When i run this : python train.py , i got this warning: 
Assign requires shapes of both tensors to match. lhs shape= [2048,3] rhs shape= [2048,21]

![image](https://user-images.githubusercontent.com/25045281/42417958-4cd1f192-82c8-11e8-9364-9c2fa77793c2.png)

do you have any idea?

**Comment by yangJirui** [comment]
I guess, you changed the CLASS_NUM(in the cfgs.py ) to 2, and you have restored the detection model with the Weights offered by us which trained in the pascal VOC. 

The solution is as follows:
Solution 1: You can load ImageNet's pretrained weights to train your data. Our program does not load the weights of Fast-RCNN/cls_fc when loading ImageNet Pretrained weights, so no error is reported.

Solution 2: Use the pre-trained model we provide to load, but you have to write some codes to control it  does not load Fast-RCNN/cls_fc, because the shape is VOC trained weights is [2048, 21] while in your model is [2048, 3].
@leetesua

**Comment by yangxue0827** [comment]
1、If you want to train your own data, please note:  
```     
(1) Modify parameters (such as CLASS_NUM, DATASET_NAME, VERSION, etc.) in $PATH_ROOT/libs/configs/cfgs.py
(2) Add category information in $PATH_ROOT/libs/label_name_dict/lable_dict.py     
(3) Add data_name to line 76 of $PATH_ROOT/data/io/read_tfrecord.py 
```   
@leetesua

**Comment by leetesua** [comment]
I have changed the VERSION in cfgs from 'FasterRCNN_20180517' to '', so it won't load anything from output/trained_weight, however, when I run train.py again, it stops, with 'restore model' as the last printed line:
![image](https://user-images.githubusercontent.com/25045281/42435875-9c5f537c-838a-11e8-9c11-e6541915ee4d.png)

also, I am a little bit confused about,,, should i change the trained_weight in output folder or pretrained_weight in data folder ?

**Comment by leetesua** [comment]
![image](https://user-images.githubusercontent.com/25045281/42436699-6eb21efc-838d-11e8-94a9-401856dfaf73.png)

**Comment by yangxue0827** [comment]
There are must something wrong with your tfrecord. @leetesua

**Comment by yangxue0827** [comment]
Check your data and xml carefully.
